### PR TITLE
make:doctrine:entities command

### PR DESCRIPTION
**Pull request by zorn-v**
It is port for `doctrine:generate:entities` command from DoctrineBundle for flex based apps.
Namespaced with "doctrine" intentionally to not conflict with "entity" so you don't have to write full command like in SensioGeneratorBundle

May be not so elegant, but this command really needed

### CODE REVIEW

**Comment by yceruto** [comment]
I guess this should be done by using `MakerInterface`, right?

**Comment by zorn-v** [comment]
Actually this not "generic" maker command. It just need to execute. I use it for generating getters/setters etc. after adding some fields/relations. Consider it as "patch for legacy" :smile: 
Maybe remove `--no-backup` option BTW ? I never revert from backup after this command yet. Project must be under version control anyway.

**Comment by Majkl578** [comment]
Please let's not add new commands based on deprecated tools (doctrine/doctrine2#6869). EntityGenerator encourages very bad practices (symfony/symfony-docs#8893) and makes the model anemic and mostly useless. That's why it should die in peace, not be used even more. 😞

**Comment by Nightbr** [comment]
Like zoonr-v said, we need to consider this as "patch for legacy". I think this is a useful feature with no alternative right now. For example, if you use ApiPlatform, you need to generate all setter/getter to expose your field. I think we should merge this and add a warning for user. And when doctrine will remove this tool, we will have find a better solution to handle this problem :)

**Comment by codedmonkey** [comment]
I'm personally 👎 on this one. While I very much agree that creating getters and setters is annoying and should be easier, EntityGenerator didn't solve that problem for me. Are you using a proper IDE? PhpStorm has built-in functionality to generate such code, and it's a pretty customizable too.

**Comment by Nightbr** [comment]
I think you never use this command... I'm using Atom with getter/setter generator plugin and sometimes phpstorm but it's very different. This command generate proper getter/setter and also add and remove functions for relations (ManyToOne, OneToMany and ManyToMany) and your IDE can't do this... 

I don't understand why we are reluctant to add feature which are usefull for developers and propose no suitable alternative...

**Comment by codedmonkey** [comment]
I have used the command, and again, I agree it's very useful to have but it wasn't the solution for me. 

I'm not a member of the Symfony team, but for now, your proposal sounds outside the scope of this bundle, we don't even have a proper interactive `make:entity` command yet. For now the best solution would be to use the code of your pull request as a separate bundle, it sounds like you're not the only one who wants this.

**Comment by Nightbr** [comment]
agreed about interactive `make:entity`, sure we need this before all 👍  

But the framework have to resolve developer problems. And what is will create here is developer will turn back to the framework and create their own solution... Pretty sad that we can find a consensus here...

IMO, I think I will create my DevBundle and integrate what is missing... 
Don't miss understand my comment, **I really love the way Symfony Flex reorganises the framework** and the structure we can use. **I already find my way to create really organized project and loved it!** I understand that Flex is young and it will be improve but we need to conduct developer in the transition.

**Comment by weaverryan** [comment]
Hi guys!

My plan is to first, enhance `make:entity` so that it is a bit more like `doctrine:generate:entity`... but better ;). Inside that command, we will generate getters & setters for the fields we add (if the user wants this). 

I think that covers *most* cases... but I think there are people who will still add new fields by hand, but want a generator to add getters & setters. That's the odd case: using the generator for only *half* of the work. I'm not sure about this yet... or if this will even be a use-case once the much-better `make:entity` (where I plan to also allow you to add fields to an existing entity) is finished.

**Comment by codedmonkey** [comment]
Personally I never liked the idea of executing generate:entities and it generating all my class files. I’m in favor of make:entity working only on single classes. if the class already exists, append the new fields. And a separate option to disable the field generator, only generate the relevant methods in that case.

**Comment by zorn-v** [comment]
@weaverryan totally agree
I urgently needed this command and I wrote this ugly "patch". Then I thought to share it. 
In particular to raise the issue of generating the entities.

**Comment by pink6440** [comment]
@codedmonkey i think generate single entity at a time and all entities are both usefull ; especially at the beginning of the project when you just had wrote your 40+ entities mappings and you have to generate the getters/setters.

**Comment by codedmonkey** [comment]
Yes I understand. I know the intention of  this bundle is to get rid of quirky namespaces, but the most semantic command names if we end up with 2 commands imo would be `make:orm-entity` and `make:orm-mappings`.

**Comment by deivid11** [comment]
An enchaced make:entity command with getters and setters generator is fine when you add a new entity from scratch, the pros of doctrine:generate:entities is that you can add more fields later by hand and then generate getters and setters. IDEs are not smart enough yet to generate methods for relationships (add, remove) doing it by hand is prone to errors

**Comment by weaverryan** [comment]
@deivid11 the idea of the enhanced `make:entity` is that it would ALSO allow you to add more fields to an existing entity. I also plan to have it handle relationships correctly (yep, adders, removers, synchronizing inverse/owning side of relation).

But yea, there still may be a use-case for people that prefer to add the fields by hand, then run one command to have all the getter/setter/adder/remover stuff generated automatically. We'll have to finish `make:entity` first and then see (at that point, it shouldn't be too much work to do it).

I'm going to close this issue, as we definitely won't use this approach. I'm working to get the `make:entity` stuff done as quickly as possible - thanks everyone for your input and patience :).

**Pull request closed without merging**
