### PR TITLE
[make:entity] Simplify repository PHPDoc removes method annotations

### PR DESCRIPTION
**Pull request by lyrixx**
I removed theses from project project, and my IDE (vscode) and PHPStan are okay with that.
It works, because doctrine has already templated the methods

### CODE REVIEW

**Review by jrushlow — APPROVED** [review]
Awesome! I'm about 99% sure that we are safe to remove the annotations now. Some SymfonyCasts folks and I tried out code completion in PHPStorm and it appears to be working just fine without them...

I'm sure the folks out there with the pitch forks will let us know pretty quick if this _does_ break something after cutting a release. :smile:

**Review by stof — APPROVED** [review]

**Comment by simondaigre** [comment]
On my end this PR broke autocompletion on PHPStorm on projects with ORM 2 (didn't tried with 3)

**Comment by lyrixx** [comment]
This is really weird, because we tested it with ORM2 and it was okay.
However, what is the version of `doctrine/persistence`?

**Comment by simondaigre** [comment]
`3.3.2`. Do you want a separate issue for this ?

**Comment by jrushlow** [comment]
@simondaigre - Yes if you could create a new issue - I'll get a patch out in the next day or so.

**Pull request merged**
