### PR TITLE
Add `--invokable` option to `make:controller`

### PR DESCRIPTION
**Pull request by adrienlucas**
Allows to create invokable controllers [as described in the documentation](https://symfony.com/doc/current/controller/service.html#invokable-controllers).

### CODE REVIEW

**Review by weaverryan — APPROVED** [review]
Waiting for the tests - but it looks nice to me!

**Comment by adrienlucas** [comment]
> Waiting for the tests - but it looks nice to me!

Fixed CS. Not sure why one of the test is failing.
Thanks for your very quick feedback!

**Comment by adrienlucas** [comment]
Second commit : the name of the template should not be `{controller_name}/index.html.twig` but rather `{controller_name}.html.twig`.
For example: `App\Controller\Blog\CreateBlogPostController` => `templates/blog/create_blog_post.html.twig`.

**Comment by weaverryan** [comment]
Awesome work - thanks for this Adrien!

**Pull request merged**
