### PR TITLE
Set table name to eliminate database keyword error

### PR DESCRIPTION
**Pull request by JakubSzczesniak**
Is really problematic for begginers to find and eliminate this problem. When we set default table name to `users` instead od `user` everything will be working.

### CODE REVIEW

**Comment by jrushlow** [comment]
I believe, correct me if I am wrong, this is related to issue #485, with a fix in PR #545 (Yet to be merged).

Is your issue covered under either the referenced issue or pending PR?

**Comment by JakubSzczesniak** [comment]
@jrushlow yes, you're right. I did this proposition, because I thought this fix will be easier and faster to merge instead of #545

**Comment by JakubSzczesniak** [comment]
@jrushlow is any change to merge this PR? Many people have problems without this. We don't know when discussion in #545 will be over...

**Comment by weaverryan** [comment]
Sorry for the delay! I'm working to merge #545 for the next release. Thanks for your attention on this detail!

**Pull request closed without merging**
