### PR TITLE
Type hints for repositories

### PR DESCRIPTION
**Pull request by enleur**
It helps IDE to get correct type if you do calls like this

```php
$user = $this->userRepository->find(1);
$user->getId(); //IDE knows that this is a User class and gives correct autocomplete
```

### CODE REVIEW

**Comment by enleur** [comment]
Should I fix code style?

**Comment by weaverryan** [comment]
Yes please :). Unless it’s recommending to use array() instead of [] - that is currently a false recommendation (we use the short syntax)

**Comment by enleur** [comment]
Done

**Comment by weaverryan** [comment]
Thank you Sergey!

**Pull request merged**
