### PR TITLE
Class not found on make:entity --regenerate

### LINKED ISSUE #207: make:entity --regenerate on existing entity class
The command "make:entity --regenerate App" correctly generates the entities (classes) the first time, when there are not yet the classes of the entities.
```
App\Entity\Myentity:
    type: entity
    table: Myentity
    id:
        id:
            type: integer
            generator:
                strategy: AUTO`
    fields:
        existingproperty:
            type: integer
```

If I add a property "newproperty" to the file entityname.orm.yml,

```
App\Entity\Myentity:
    type: entity
    table: Myentity
    id:
        id:
            type: integer
            generator:
                strategy: AUTO`
    fields:
        existingproperty:
            type: integer
        newproperty:
            type: boolean
            nullable: true
```
 when I execute the command I get this error:
> Property App\Entity\Myentity::$newproperty does not exist

The workaround is to add property to the class:
```
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;

class Myentity
{

    private $newproperty;
```
In this case, if i run "make:entity --regenerate App", the command correctly generate getter and setter.
It Is a bug or it is correct that it works like that?

Thanks for your work

### PR DESCRIPTION
**Pull request by mertoksuz**
That PR fixes #207.

### CODE REVIEW

**Comment by weaverryan** [comment]
Hey @mertoksuz!

Thanks for making this PR to fix this! But, the tests are failing because the old exception class *is* needed in the catch. Can why your change fixes things? It's quite possible that we may need to catch *both* `MappingException`.

Cheers!

**Comment by mertoksuz** [comment]
@weaverryan 

Hey, i updated my codes. Is that recover both exceptions ?

**Comment by weaverryan** [comment]
@mertoksuz thanks! You did well! But, we can't use the `|` syntax in catch - it breaks in 7.0. Can you manually add 2 separate catches - one for each exception?

And also, do you have any idea why the `Common` exception is the one that fixes your problem? I'll tag a release shortly - as you are working quickly, we can hopefully include this :)

**Comment by mertoksuz** [comment]
@weaverryan 

i updated again :). 

I think, when doctrine tries to load metadata somehow it checks php classes but if you have only yml/xml files for entities than it throws Class not found ( MappingException ).

**Comment by weaverryan** [comment]
Thanks for the quick work @mertoksuz!

**Pull request merged**
