### PR TITLE
Allow deprecation-contracts 3

### PR DESCRIPTION
**Pull request by derrabus**
Fixes #1023

### CODE REVIEW

**Review by stof — APPROVED** [review]

**Comment by derrabus** [comment]
I think, we have to release DoctrineBundle to fix the CI here.

**Comment by derrabus** [comment]
Done, let's try this again.

**Comment by derrabus** [comment]
Okay, that rabbit hole is a bit deeper than I thought.

symfony/panther#519

**Comment by weaverryan** [comment]
Thanks @derrabus! I'll get a release out asap, there are a few other Sf6 bugs that didn't show up in our tests for some reason until the stable release. But I aim to do it today.

**Pull request closed without merging**
