### PR TITLE
make:crud skeleton optimization

### PR DESCRIPTION
**Pull request by sadikoff**
Lets start from `Controller::delete` action. I don't think we need 2 return statements here.

Maybe it will be better to add some flash messages?

### CODE REVIEW

**Comment by sadikoff** [comment]
I think we don't need to know if the user is printing them or not, We just add them in `index` and `edit` templates and each user will decide to use it or not.

**Comment by weaverryan** [comment]
@sadikoff I'm not sure about printing the flash messages in `index.html.twig` and `edit.html.twig`... because the user will *always* need to remove those... as flash messages should *really* live in the base layout.... That's what complicates things for me.

**Comment by sadikoff** [comment]
@weaverryan maybe than we can ask user to use flash or not, and inject them in `base` layout including something like `_flash.html.twig`?

**Comment by weaverryan** [comment]
@sadikoff We don't have any ability to modify Twig files right now. Also, I want to avoid asking unnecessary questions.... but *maybe* we should ask them if they want flash messages or not.

Currently, I'm leaning towards this: we always add flash messages in the controller. Then, we can do a quick check in their `base.html.twig`: if we do not see the flash messages being printed there (we could do some simple string check, not perfect, but good enough), we could print out a warning that tells them they should add this to their base.html.twig.

**Comment by sadikoff** [comment]
@weaverryan If you don't mind lets merge this PR. It will fix some bugs. After I will prepare PR for flash messages and we will discuss it there.

**Comment by weaverryan** [comment]
Thank you Vladimir!

**Pull request merged**
