### PR TITLE
[make:registration] URL should be escaped

### PR DESCRIPTION
**Pull request by Seldaek**

### CODE REVIEW

**Review by jrushlow — APPROVED** [review]
Thanks @Seldaek

**Comment by OskarStark** [comment]
@Seldaek the commit and the PR title confused me a bit, can you please fix this?

One is talking about escaping and the other one about not escaping.

thanks

**Comment by Seldaek** [comment]
Yeah sorry I brain-farted the commit message and noticed too late... can you perhaps do a squash merge and fix the commit message there? :) Don't really feel like cloning this and rebasing etc just to fix a typo sorry..

**Comment by OskarStark** [comment]
I think we can, thanks!

**Comment by weaverryan** [comment]
> Don't really feel like cloning this and rebasing etc just to fix a typo sorry..

FINE! Just kidding - thanks for taking the time to make the PR in the first place Jordi - I tweaked the commit message :).

Cheers!

**Pull request merged**
