### PR TITLE
Add a wizard emoji

### PR DESCRIPTION
**Pull request by tgalopin**
🧙

### CODE REVIEW

**Comment by lyrixx** [comment]
How does it behave on system that does not support it? (we may don't care :) )

**Comment by javiereguiluz** [comment]
Does anyone see a wizard here?

error-1

error-2

**Comment by tgalopin** [comment]
Updated :)

**Comment by nicolas-grekas** [comment]
@javiereguiluz 
image

**Comment by javiereguiluz** [comment]
@tgalopin I'm on a macOS computer and still can't see this emoji:

error-3

**Comment by javiereguiluz** [comment]
@tgalopin yes, I can see all emojis perfectly ... but not the one you added here. I only see an empty square.

**Comment by ogizanagi** [comment]
@javiereguiluz : You might still be on OS X Sierra, but this emoji is part of Unicode 10 for which the Apple Color Emoji font was only updated since High Sierra.

**Comment by javiereguiluz** [comment]
@ogizanagi you are right ... and that was my point: we may be trying to use a too new emoji ... which is not seen by some (lots?) of users. Please, think twice before merging it 🙏  Thanks!

**Comment by nicolas-grekas** [comment]
As time passes, this compat issue will disappear. Given the outcome is a simple square, I'm all for merging this now :)

**Comment by weaverryan** [comment]
We did it! Thanks Tito ;)

**Pull request closed without merging**
