### PR TITLE
[WIP] adding DisableAutoMapping code to registration form

### PR DESCRIPTION
**Pull request by weaverryan**
If/when we merge the auto-validation recipe, the `make:registration-form` should disable validation on the `password` field. We could/should also try to add the annotation in `make:user` (but it's only possible if you already have the validator installed).

### CODE REVIEW

**Comment by weaverryan** [comment]
This should be more-or-less done, but it's blocked by symfony/symfony#34694 and I also opened symfony/symfony#34860

**Comment by dunglas** [comment]
Can't this one be merged now?

**Comment by weaverryan** [comment]
I think this isn't "really" needed, as the auto-validation is "opt in" and I think most people are not enabling it globally anyways.

**Comment by dunglas** [comment]
We cannot enable it by default in the recipe because this PR isn't merge. Everything else is ready.

**Pull request closed without merging**
