### PR TITLE
fix: add src option for not standard paths

### PR DESCRIPTION
**Pull request by rampmaster**
I add custom option `src` for entity generator

### CODE REVIEW

**Comment by weaverryan** [comment]
Hi there!

I agree that we can make this better :). But, I think there is a different solution that is better for DX. Instead of using Finder to look in the src/ directory, we should read the Doctrine metadata to load a real list of all of the entities. This should not be too difficult by using the DoctrineHelper class. Then, you will get the nice functionality without needing to know about or pass an option.

Do you want to update your PR to try this?

Cheers!

**Comment by rampmaster** [comment]
Yes, not problem @weaverryan and thanks for your idea :-)

**Comment by mssimi** [comment]
@rampmaster Hey, any chance updating this PR? I need this feature.

**Comment by rampmaster** [comment]
Yes, working.

**Comment by bastos71** [comment]
Hi @rampmaster ! I was about to create the same fix ^^
When this PR would be finish and accepted ?

**Comment by weaverryan** [comment]
Closing in favor of #310 or #311

**Pull request closed without merging**
