### PR TITLE
[Voter] Add entity class only if it exists

### PR DESCRIPTION
**Pull request by yceruto**
This is not ideal yet, but at least will avoid generating a broken voter class.

### CODE REVIEW

**Comment by yceruto** [comment]
This is considered as a bugfix?

**Comment by yceruto** [comment]
This is considered as a bugfix?

**Comment by javiereguiluz** [comment]
Quick question: if we don't do this change and `App\Entity\Blog` doesn't exist, does PHP fail when compiling the voter class or when using it? If it's when using it, I don't care about this because user MUST change the voter class before using it, so changing the entity class is just another thing they must do.

**Comment by yceruto** [comment]
> if we don't do this change and App\Entity\Blog doesn't exist, does PHP fail when compiling the voter class or when using it?

No. so closing this.

**Pull request closed without merging**
