### PR TITLE
[Entity] Made repository generation optional (true by default) and add namespace changement

### LINKED ISSUE #31: Namespaces and repository classes
Some questions:

1.  Is that possible to create entities or controllers with namespaces?
2.  How to disable creating repository class while making doctrine entity?

### PR DESCRIPTION
**Pull request by Simperfit**
This fixes #31 
It is now possible to generate an entity without a repository and with a custom namespace

### CODE REVIEW

**Comment by javiereguiluz** [comment]
Not sure about this. Simplicity is the main (and the best) feature of this bundle. We want to include options for everything. They provide flexibility ... but they complicate everything.

Next time is better to wait until the related issue (#31 in this case) is approved or rejected. Thanks!

**Comment by Simperfit** [comment]
I totally understand your point ! Thanks for looking at the PR ;).

**Comment by fabpot** [comment]
I think it is indeed not worth it. If one does not want the repository, he can delete the file. Sounds easy enough.

**Comment by weaverryan** [comment]
Closing for the reasons listed above. Thanks @Simperfit!

**Pull request closed without merging**
