### PR TITLE
Fix: Rendering issue

### PR DESCRIPTION
**Pull request by OskarStark**
Before:
CleanShot 2021-01-21 at 21 04 35

After:
CleanShot 2021-01-21 at 21 04 54

Same for the other methods

### CODE REVIEW

**Review by jrushlow — APPROVED** [review]
Good Catch! Thanks @OskarStark

**Review by Superkooka — APPROVED** [review]

**Comment by weaverryan** [comment]
Thanks Oskar!

**Comment by OskarStark** [comment]
Can be closed?

**Comment by weaverryan** [comment]
Definitely - I'm not sure why it didn't close for me.

**Pull request closed without merging**
