### PR TITLE
Added Event Listener generation command.

### PR DESCRIPTION
**Pull request by piotrgradzinski**
May be useful to create an Event Listener using make command.

### CODE REVIEW

**Comment by weaverryan** [comment]
Thanks for the PR! This seems logical, but I’m -1. Event listeners require service config to work, and I don’t want beginners to be confused and not know which maker command to use.

**Comment by nicolas-grekas** [comment]
I agree with Ryan: making a subscriber is a better option because it is self describing, thus auto configurable.

**Comment by piotrgradzinski** [comment]
@nicolas-grekas, @weaverryan - sure that making a subscriber is a better option mainly due to configuration option. I have to admit that having to copy/paste additional code to `services.yaml` is a pain. 

If you don't see the space for this PR please close it :)

**Comment by weaverryan** [comment]
Closing now :). But I hope to see more PR’s in the future!

**Comment by piotrgradzinski** [comment]
@weaverryan - sure, actually working on some commands from #17 issue :)

**Comment by javiereguiluz** [comment]
@piotrgradzinski thanks for your willingness to contribute ... but let's slow down a bit. We're going to add more commands, but not immediately. Let' fix first all the current issues, problems and bad choices. Thanks!

**Pull request closed without merging**
