### PR TITLE
[make:crud] Rename `add` method of repository to `save`.

### PR DESCRIPTION
**Pull request by bdaler**
- rename `add` method of repository to `save`
- https://github.com/symfony/maker-bundle/issues/1138

### CODE REVIEW

**Comment by jrushlow** [comment]
@bdaler I just merged in a few CI fixes, can you do a rebase please?

**Review by jrushlow — CHANGES_REQUESTED** [review]
Looks good to me, we just need passing tests that are related to this PR.

**Comment by weaverryan** [comment]
Ping @garak who originally proposed the methods in #788. I don't really care what the methods are called - but I don't like changing them over and over again. So if we are going to make this change, we need some agreement that this is how it should be named.

**Comment by garak** [comment]
IMHO "add" is more consistent with the concept of collection, but I don't have anything against "save"

**Comment by jrushlow** [comment]
The commit history looks a bit mashed up in this PR. Closing in favor of #1204 which contains cherry-picked changes from this PR.

**Pull request closed without merging**
