### PR TITLE
Adding Entity attribute support

### PR DESCRIPTION
**Pull request by weaverryan**
Hi!

This is #920 cleaned up.

Somehow, in that PR, the commits got tanged. For example, some commits were done twice, like https://github.com/SimonMarx/maker-bundle/commit/d12c2f9eb227ad7e34b43d0dbec33c97bddf9d71 and https://github.com/SimonMarx/maker-bundle/commit/3848f4fc77f12abf036d02a8ffc65569f4d47e00 - but the bigger problem is that some commits (like the 2nd listed) have one date on GitHub (e.g. Aug 12th) but another date when pulled down locally (July 4th). Whatever is causing this seems to also cause, during a rebase, for these commits to be rebased on reverse. In short, it was an odd mess.

To fix this, I've created a single commit with co-authors. I need to verify that this is ok with @SimonMarx and determine where these other two contributors came from :) (see https://github.com/symfony/maker-bundle/pull/920#issuecomment-926640859)

Cheers!

```
Co-authored-by: Simon Marx <s.marx@shopmacher.de>
Co-authored-by: Morgan ABRAHAM <morgan@geekimo.me>
Co-authored-by: Adria Lopez <adria@prealfa.com>
Co-authored-by: Jesse Rushlow <jr@rushlow.dev>
```

### CODE REVIEW

**Comment by SimonMarx** [comment]
@weaverryan For what exactly do you need my "ok" :smile: ?

**Comment by weaverryan** [comment]
Just wanted you to see that I squashed all your commits and set you as a co-author :). It was the best I could do to clean things up but still give credit to everyone.

**Comment by SimonMarx** [comment]
Whatever this means, im totally fine with it. Let's bring the feature out there, no matter what the git history says :) Hopefully my next PR won't make a mess which you have to cleanup ;/

**Comment by weaverryan** [comment]
Thank you @SimonMarx, @Geekimo, @adlpz & @jrushlow for contributing to this!

**Pull request merged**
