### PR TITLE
Use ManagerRegistry interface from doctrine

### PR DESCRIPTION
**Pull request by hason**

### CODE REVIEW

**Comment by romaricdrigon** [comment]
Thank you for taking time to create a PR.
Could you please explain he différence, and eventually the issue you had?

**Comment by nicolas-grekas** [comment]
`Symfony\Bridge\Doctrine\ManagerRegistry` has been removed from SF5 :)

**Comment by romaricdrigon** [comment]
Great, thanks for the explanation :)

**Comment by weaverryan** [comment]
Thank you @hason!

**Pull request merged**
