### PR TITLE
[make:entity] Change getter PHPDoc return type on Collection

### PR DESCRIPTION
**Pull request by mehdibo**
Improves #979

### CODE REVIEW

**Comment by mehdibo** [comment]
Oops, still need more fixing

**Comment by mehdibo** [comment]
Let me know if I caused the tests to fail, looks like they are not related to my changes

**Comment by allan-simon** [comment]
Is there something that can be done to help this pull request to move forward,  this will help making the autogenerated code already compliant with phpstan checks , which would be a blessing :)

**Comment by weaverryan** [comment]
Awesome! Thank you Mehdi!

**Pull request merged**
