### PR TITLE
allow symfony6

### PR DESCRIPTION
**Pull request by tacman**

### CODE REVIEW

**Comment by weaverryan** [comment]
Yup, time to get this going - thanks for getting us kicked off @tacman!

**Comment by derrabus** [comment]
This is the single remaining package that needs to be updated to make `symfony/website-skeleton` work for the 6.0 branch.

But… no pressure. 😉

**Comment by weaverryan** [comment]
Thanks for getting this going @tacman (it's been on my list!). I'm taking over now - these final details are complex, and often due to how I designed the bundle in the past ;).

**Comment by weaverryan** [comment]
Thank you for getting this rolling Tac!

**Pull request merged**
