### PR TITLE
Fix the indentation in the subscriber template

### PR DESCRIPTION
**Pull request by nesk**

### CODE REVIEW

**Comment by mdeletter** [comment]
PR verified. This  small change can be merged.

**Comment by wesselvanderlinden** [comment]
I agree with @mdeletter, but I wonder why the code style checker didn't complain about the missing space before. Maybe you should also add a phpcs rule?

**Comment by mikelerch** [comment]
I completely agree with @mdeletter. I also verify this PR.

**Comment by huib0029** [comment]
I completely disagree, because I had too much beer, but nevermind

**Comment by nesk** [comment]
Is there anything missing which prevents this PR from being merged?

**Comment by weaverryan** [comment]
Just waiting on me! :) Thank you @nesk! I'm also wondering why teh style-checker in the CI didn't catch this...

**Pull request merged**
