### PR TITLE
Escape hashtag in yaml

### LINKED ISSUE #373: make:auth returns YamlSourceManipulator error
I'm trying to make a login form authenticator via the  `make:auth` command, following this article : [https://symfony.com/doc/current/security/form_login_setup.html](https://symfony.com/doc/current/security/form_login_setup.html), but i'm facing this error :

```
# bin/console make:auth -vvv

 What style of authentication do you want? [Empty authenticator]:
  [0] Empty authenticator
  [1] Login form authenticator
 > 1

 The class name of the authenticator to create (e.g. AppCustomAuthenticator):
 > LoginFormAuthenticator

 Which firewall do you want to update? [admin]:
  [0] admin
  [1] main
 > 1

 Choose a name for the controller class (e.g. SecurityController) [SecurityController]:
 > SecurityController

 Enter the User class that you want to authenticate (e.g. App\Entity\User) [App\Entity\User]:
 > App\Entity\User


In YamlSourceManipulator.php line 768:
                                               
  [ErrorException]                             
  Warning: preg_match(): Unknown modifier 'G'  
                                               

Exception trace:
 () at /app/vendor/symfony/maker-bundle/src/Util/YamlSourceManipulator.php:768
 Symfony\Bundle\MakerBundle\Util\YamlSourceManipulator->findEndPositionOfValue() at /app/vendor/symfony/maker-bundle/src/Util/YamlSourceManipulator.php:499
 Symfony\Bundle\MakerBundle\Util\YamlSourceManipulator->advanceBeyondValue() at /app/vendor/symfony/maker-bundle/src/Util/YamlSourceManipulator.php:214
 Symfony\Bundle\MakerBundle\Util\YamlSourceManipulator->updateData() at /app/vendor/symfony/maker-bundle/src/Util/YamlSourceManipulator.php:206
 Symfony\Bundle\MakerBundle\Util\YamlSourceManipulator->updateData() at /app/vendor/symfony/maker-bundle/src/Util/YamlSourceManipulator.php:206
 Symfony\Bundle\MakerBundle\Util\YamlSourceManipulator->updateData() at /app/vendor/symfony/maker-bundle/src/Util/YamlSourceManipulator.php:206
 Symfony\Bundle\MakerBundle\Util\YamlSourceManipulator->updateData() at /app/vendor/symfony/maker-bundle/src/Util/YamlSourceManipulator.php:206
 Symfony\Bundle\MakerBundle\Util\YamlSourceManipulator->updateData() at /app/vendor/symfony/maker-bundle/src/Util/YamlSourceManipulator.php:206
 Symfony\Bundle\MakerBundle\Util\YamlSourceManipulator->updateData() at /app/vendor/symfony/maker-bundle/src/Util/YamlSourceManipulator.php:206
 Symfony\Bundle\MakerBundle\Util\YamlSourceManipulator->updateData() at /app/vendor/symfony/maker-bundle/src/Util/YamlSourceManipulator.php:88
 Symfony\Bundle\MakerBundle\Util\YamlSourceManipulator->setData() at /app/vendor/symfony/maker-bundle/src/Security/SecurityConfigUpdater.php:84
 Symfony\Bundle\MakerBundle\Security\SecurityConfigUpdater->updateForAuthenticator() at /app/vendor/symfony/maker-bundle/src/Maker/MakeAuthenticator.php:190
 Symfony\Bundle\MakerBundle\Maker\MakeAuthenticator->generate() at /app/vendor/symfony/maker-bundle/src/Command/MakerCommand.php:104
 Symfony\Bundle\MakerBundle\Command\MakerCommand->execute() at /app/vendor/symfony/console/Command/Command.php:255
 Symfony\Component\Console\Command\Command->run() at /app/vendor/symfony/console/Application.php:926
 Symfony\Component\Console\Application->doRunCommand() at /app/vendor/symfony/framework-bundle/Console/Application.php:89
 Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at /app/vendor/symfony/console/Application.php:269
 Symfony\Component\Console\Application->doRun() at /app/vendor/symfony/framework-bundle/Console/Application.php:75
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /app/vendor/symfony/console/Application.php:145
 Symfony\Component\Console\Application->run() at /app/bin/console:38
```

The Symfony 4.2 install is fresh from today, make bundle in version 1.11.4

Thanks

### PR DESCRIPTION
**Pull request by LeJeanbono**
Fix #373

### CODE REVIEW

**Comment by weaverryan** [comment]
Hey @LeJeanbono!

This is impressive. Seriously, that class is a BEAST, so nice job getting into it. The fix works on all versions *except* for PHP 7.3 (see the build failure). Can you check into it?

Thanks!

**Comment by weaverryan** [comment]
Ping! Still a failure on 7.3 🤔

**Comment by LeJeanbono** [comment]
I think it's a problem with PCRE with preg_match in 7.3
I saw something with comments : https://www.php.net/manual/en/regexp.reference.comments.php

**Comment by weaverryan** [comment]
Thank you @LeJeanbono!

**Pull request merged**
