### PR TITLE
Update index.rst

### PR DESCRIPTION
**Pull request by tavy315**
$ composer require maker --dev

  [InvalidArgumentException]
  Could not find package maker.

  Did you mean one of these?
      yab/crudmaker
      yab/formmaker
      greabock/maker
      osflab/doc-maker
      nickwest/form-maker

### CODE REVIEW

**Comment by stof** [comment]
This example in the readme assumes that this is used in a Flex project (flex will make `maker` work)

**Comment by weaverryan** [comment]
Hmm. Stof is correct. The question is, should we use the longer, but more universal package name?

**Comment by tavy315** [comment]
Documentation for all the rest of the bundles use the longer package name (ex: https://symfony.com/doc/current/bundles/DoctrineBundle/installation.html, https://symfony.com/doc/current/bundles/SensioFrameworkExtraBundle/index.html, https://symfony.com/doc/current/bundles/SensioGeneratorBundle/index.html etc).

**Comment by weaverryan** [comment]
Yea, let's use the version that works for everyone :). Thanks @tavy315!

**Pull request merged**
