### PR TITLE
Use a better exception when using make:auth with a form

### PR DESCRIPTION
**Pull request by lyrixx**

### CODE REVIEW

**Comment by romaricdrigon** [comment]
Hello,

I have some mixed feelings about using a `BadMethodCallException`.
From PHP manual, `Exception thrown if a callback refers to an undefined method or if some arguments are missing.`, I feel like we don't quite have the same semantic.
Is there any reason why this exception is better? 
Personally, I would prefer a `LogicException`.

**Comment by lyrixx** [comment]
Anyway, just exception is not cool

**Comment by romaricdrigon** [comment]
Sure. Then could you please modify with `LogicException`, and fix failing test?
Thank you

**Comment by lyrixx** [comment]
I fixed it, but it seems that tests are broken

**Comment by lyrixx** [comment]
ping @romaricdrigon

**Comment by weaverryan** [comment]
Thanks Grégoire!

**Pull request merged**
