### PR TITLE
Fixed CS of generated entity

### PR DESCRIPTION
**Pull request by lyrixx**

### CODE REVIEW

**Comment by javiereguiluz** [comment]
For what it's worth, in the Symfony Docs we don't add parenthesis when there's no arguments. Example: https://symfony.com/doc/current/doctrine.html#creating-an-entity-class

Maybe we must change Symfony Docs. I'm not sure.

**Comment by lyrixx** [comment]
> Maybe we must change Symfony Docs. I'm not sure.

I think. We never use `$date = new DateTime`. It's the same for annotation ;)

**Comment by weaverryan** [comment]
This is cool with me - I slightly prefer with `()`

**Comment by weaverryan** [comment]
Thanks Grégoire!

**Pull request merged**
